all:
  hosts:
    cp1:
      ansible_host: 51.250.21.26
      ip: 10.129.0.11
    node1:
      ansible_host: 84.201.162.74
      ip: 10.129.0.6
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
