apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: 7zgymko/front:v1
        imagePullPolicy: IfNotPresent
        name: front
        env:
          - name: BASE_URL
            value: "http://localhost:9000"

